### PR TITLE
Update ElasticsearchEngine.php

### PR DESCRIPTION
**Pull request by intech**
there are so many questions:
1. The search is too easy, it will not work in the medium and complex queries, because it would require a specific mapping format.
2. I replaced all the demands of the bulk, otherwise there would have been problems.
3. You can not specify a limit of 10,000 for this purpose there is a special function scroll. Do not forget the memory, a document can be too high, with the full sample elastic overflow memory work and protective gear java, which kills the thread thus translog not be able to ensure the integrity of operations at the time.

### CODE REVIEW

**Comment by hernandev** [comment]
@intech have you ran the unit tests? just making sure before merging

**Comment by intech** [comment]
@hernandev No, did not check if you have the opportunity to start testing right now, please do it for me, and report the results.
I think I wrote the code correctly, edited it right here on github. ;)

**Comment by hernandev** [comment]
Reverted since it was not indexing correctly, gonna test and give you feedback

**Comment by intech** [comment]
@hernandev, thx!
```bash
1) Tests\ElasticsearchEngineTest::test_update_adds_objects_to_index
BadMethodCallException: Method Mockery_3_Elasticsearch_Client::bulk() does not exist on this mock object
/home/travis/build/laravel/scout/src/Engines/ElasticsearchEngine.php:48
/home/travis/build/laravel/scout/tests/ElasticsearchEngineTest.php:24
```
Any ideas why test function is not visible?

**Comment by intech** [comment]
https://github.com/elastic/elasticsearch-php/blob/master/docs/crud.asciidoc#bulk-indexing all right, hm...

**Comment by hernandev** [comment]
The mock itself only expose methods you use on shouldReceive, is not the real client, only a fake object that will simulate the elasticsearch client, so whatever the engine is passing the the $client, it should be expected on the test
$client->shouldReceive('build')->with($thedatathatwillbepassedexatctlyequal)

**Pull request merged**
